export const CREATE_BUG_SUCCESS = "GREATE_BUG_SUCCESS";
export const UPDATE_BUG_SUCCESS = "UPDATE_BUG_SUCCESS";
export const LOAD_BUG_SUCCESS = "LOAD_BUG_SUCCESS";
export const LOAD_LANGUAGE_SUCCESS = "LOAD_LANGUAGE_SUCCESS";
export const LOAD_FRAMEWORK_SUCCESS = "LOAD_FRAMEWORK_SUCCESS";
export const LOAD_LIBRARY_SUCCESS = "LOAD_LIBRARY_SUCCESS";
